
// Generated by js_of_ocaml 2.7
(function(w){"use strict";var
L="Sys_error",X=224,W="Invalid_argument",l=1024,K=57343,V=512,U="End_of_file",T="Failure",J="Undefined_recursive_module",S="Stack_overflow",e=128,d="",s=" : file already exists",G=56320,H=240,I=2048,a=248,R="Not_found",E="Assert_failure",F="/",P="Sys_blocked_io",Q="fd ",D="Out_of_memory",O="Match_failure",N="Division_by_zero",M=1e3,aA=0;function
m(){return aA++}function
aE(a,b){if(b.repeat)return b.repeat(a);var
c=d,e=0;if(a==0)return c;for(;;){if(a&1)c+=b;a>>=1;if(a==0)return c;b+=b;e++;if(e==9)b.slice(0,1)}}function
ah(a,b,c){var
e=new
Array(c);for(var
d=0;d<c;d++)e[d]=a[b+d];return e}function
v(a,b,c){var
e=String.fromCharCode;if(b==0&&c<=4096&&c==a.length)return e.apply(null,a);var
f=d;for(;0<c;b+=l,c-=l)f+=e.apply(null,ah(a,b,Math.min(c,l)));return f}function
_(a){if(a.t==2)a.c+=aE(a.l-a.c.length,"\0");else
a.c=v(a.c,0,a.c.length);a.t=0}function
aa(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>127)return false;return true}else
return!/[^\x00-\x7f]/.test(a)}function
aJ(a){for(var
m=d,f=d,i,h,j,b,c=0,k=a.length;c<k;c++){h=a.charCodeAt(c);if(h<e){for(var
g=c+1;g<k&&(h=a.charCodeAt(g))<e;g++);if(g-c>V){f.substr(0,1);m+=f;f=d;m+=a.slice(c,g)}else
f+=a.slice(c,g);if(g==k)break;c=g}b=1;if(++c<k&&((j=a.charCodeAt(c))&-64)==e){i=j+(h<<6);if(h<X){b=i-12416;if(b<e)b=1}else{b=2;if(++c<k&&((j=a.charCodeAt(c))&-64)==e){i=j+(i<<6);if(h<H){b=i-925824;if(b<I||b>=55295&&b<57344)b=2}else{b=3;if(++c<k&&((j=a.charCodeAt(c))&-64)==e&&h<245){b=j-63447168+(i<<6);if(b<65536||b>1114111)b=3}}}}}if(b<4){c-=b;f+="\ufffd"}else
if(b>65535)f+=String.fromCharCode(55232+(b>>10),G+(b&1023));else
f+=String.fromCharCode(b);if(f.length>l){f.substr(0,1);m+=f;f=d}}return m+f}function
aI(a){switch(a.t){case
9:return a.c;default:_(a);case
0:if(aa(a.c)){a.t=9;return a.c}a.t=8;case
8:return aJ(a.c)}}function
h(a,b,c){this.t=a;this.c=b;this.l=c}h.prototype.toString=function(){return aI(this)};function
ag(a){if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
b=w.console;b&&b.error&&b.error(a)}function
as(a){ag("caml_js_expr: fallback to runtime evaluation");return eval(a.toString())}function
at(a){return ah(a,1,a.length-1)}function
au(a,b){return a.apply(null,at(b))}function
aK(a){for(var
h=d,c=h,b,j,f=0,i=a.length;f<i;f++){b=a.charCodeAt(f);if(b<e){for(var
g=f+1;g<i&&(b=a.charCodeAt(g))<e;g++);if(g-f>V){c.substr(0,1);h+=c;c=d;h+=a.slice(f,g)}else
c+=a.slice(f,g);if(g==i)break;f=g}if(b<I){c+=String.fromCharCode(192|b>>6);c+=String.fromCharCode(e|b&63)}else
if(b<55296||b>=K)c+=String.fromCharCode(X|b>>12,e|b>>6&63,e|b&63);else
if(b>=56319||f+1==i||(j=a.charCodeAt(f+1))<G||j>K)c+="\xef\xbf\xbd";else{f++;b=(b<<10)+j-56613888;c+=String.fromCharCode(H|b>>18,e|b>>12&63,e|b>>6&63,e|b&63)}if(c.length>l){c.substr(0,1);h+=c;c=d}}return h+c}function
ab(a){var
b=9;if(!aa(a))b=8,a=aK(a);return new
h(b,a,a.length)}function
aB(a,b){throw[0,a,b]}function
c(a){return new
h(0,a,a.length)}function
ae(a,b){aB(a,c(b))}var
f=[0];function
g(a){ae(f.Sys_error,a)}function
av(a){if(!a.opened)g("Cannot flush a closed channel");if(a.buffer==d)return 0;if(a.output)switch(a.output.length){case
2:a.output(a,a.buffer);break;default:a.output(a.buffer)}a.buffer=d;return 0}function
$(a){ae(f.Invalid_argument,a)}function
k(a){if(a<0)$("String.create");return new
h(a?2:9,d,a)}var
af=0;function
aM(){return new
Date().getTime()/M}function
x(){return Math.floor(aM())}function
i(a){this.data=a;this.inode=af++;var
b=x();this.atime=b;this.mtime=b;this.ctime=b}i.prototype={truncate:function(){this.data=k(0);this.modified()},modified:function(){var
a=x();this.atime=a;this.mtime=a}};function
u(a){return a.l}function
ad(a){a=a
instanceof
h?a.toString():a;g(a+": No such file or directory")}var
aq=F;function
o(a){a=a
instanceof
h?a.toString():a;if(a.charCodeAt(0)!=47)a=aq+a;var
e=a.split(F),b=[];for(var
c=0;c<e.length;c++)switch(e[c]){case"..":if(b.length>1)b.pop();break;case".":break;case"":if(b.length==0)b.push(d);break;default:b.push(e[c]);break}b.orig=a;return b}function
j(){this.content={};this.inode=af++;var
a=x();this.atime=a;this.mtime=a;this.ctime=a}j.prototype={exists:function(a){return this.content[a]?1:0},mk:function(a,b){this.content[a]=b},get:function(a){return this.content[a]},list:function(){var
a=[];for(var
b
in
this.content)a.push(b);return a},remove:function(a){delete
this.content[a]}};var
q=new
j();q.mk(d,new
j());function
t(a){var
b=q;for(var
c=0;c<a.length;c++){if(!(b.exists&&b.exists(a[c])))ad(a.orig);b=b.get(a[c])}return b}function
aH(a){var
c=o(a),b=t(c);return b
instanceof
j?1:0}function
aF(a){return new
h(4,a,a.length)}function
Z(a){var
c=new
Array(a.l),e=a.c,d=e.length,b=0;for(;b<d;b++)c[b]=e.charCodeAt(b);for(d=a.l;b<d;b++)c[b]=0;a.c=c;a.t=4;return c}function
aN(a){if(a.t!=4)Z(a);return a.c}function
ar(a,b){var
f=o(a),d=q;for(var
k=0;k<f.length-1;k++){var
e=f[k];if(!d.exists(e))d.mk(e,new
j());d=d.get(e);if(!(d
instanceof
j))g(f.orig+s)}var
e=f[f.length-1];if(d.exists(e))g(f.orig+s);if(b
instanceof
j)d.mk(e,b);else
if(b
instanceof
i)d.mk(e,b);else
if(b
instanceof
h)d.mk(e,new
i(b));else
if(b
instanceof
Array)d.mk(e,new
i(aF(b)));else
if(b.toString)d.mk(e,new
i(c(b.toString())));else
$("caml_fs_register");return 0}function
aG(a){var
b=q,d=o(a),e,f;for(var
c=0;c<d.length;c++){if(b.auto){e=b.auto;f=c}if(!(b.exists&&b.exists(d[c])))return e?e(d,f):0;b=b.get(d[c])}return 1}function
n(a,b,c){if(f.fds===undefined)f.fds=new
Array();c=c?c:{};var
d={};d.file=b;d.offset=c.append?u(b.data):0;d.flags=c;f.fds[a]=d;f.fd_last_idx=a;return a}function
aO(a,b,c){var
d={};while(b){switch(b[1]){case
0:d.rdonly=1;break;case
1:d.wronly=1;break;case
2:d.append=1;break;case
3:d.create=1;break;case
4:d.truncate=1;break;case
5:d.excl=1;break;case
6:d.binary=1;break;case
7:d.text=1;break;case
8:d.nonblock=1;break}b=b[2]}var
h=a.toString(),j=o(a);if(d.rdonly&&d.wronly)g(h+" : flags Open_rdonly and Open_wronly are not compatible");if(d.text&&d.binary)g(h+" : flags Open_text and Open_binary are not compatible");if(aG(a)){if(aH(a))g(h+" : is a directory");if(d.create&&d.excl)g(h+s);var
i=f.fd_last_idx?f.fd_last_idx:0,e=t(j);if(d.truncate)e.truncate();return n(i+1,e,d)}else
if(d.create){var
i=f.fd_last_idx?f.fd_last_idx:0;ar(a,k(0));var
e=t(j);return n(i+1,e,d)}else
ad(a)}n(0,new
i(k(0)));n(1,new
i(k(0)));n(2,new
i(k(0)));function
aw(a){var
b=f.fds[a];if(b.flags.wronly)g(Q+a+" is writeonly");return{file:b.file,offset:b.offset,fd:a,opened:true,refill:null}}function
Y(a,b,c,d,e){if(e==0)return 0;if(d==0&&(e>=c.l||c.t==2&&e>=c.c.length)){c.c=a.t==4?v(a.c,b,e):b==0&&a.c.length==e?a.c:a.c.substr(b,e);c.t=c.c.length==c.l?0:2}else
if(c.t==2&&d==c.c.length){c.c+=a.t==4?v(a.c,b,e):b==0&&a.c.length==e?a.c:a.c.substr(b,e);c.t=c.c.length==c.l?0:2}else{if(c.t!=4)Z(c);var
g=a.c,h=c.c;if(a.t==4)for(var
f=0;f<e;f++)h[d+f]=g[b+f];else{var
i=Math.min(e,g.length-b);for(var
f=0;f<i;f++)h[d+f]=g.charCodeAt(b+f);for(;f<e;f++)h[d+f]=0}}return 0}function
aL(a){if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
b=w.console;b&&b.log&&b.log(a)}var
p=new
Array();function
aD(a,b){var
h=c(b),d=u(h),g=u(a.file.data),f=a.offset;if(f+d>=g){var
e=k(f+d);Y(a.file.data,0,e,0,g);Y(h,0,e,f,d);a.file.data=e}a.offset+=d;a.file.modified();return 0}function
ac(a){var
b;switch(a){case
1:b=aL;break;case
2:b=ag;break;default:b=aD}var
e=f.fds[a];if(e.flags.rdonly)g(Q+a+" is readonly");var
c={file:e.file,offset:e.offset,fd:a,opened:true,buffer:d,output:b};p[c.fd]=c;return c}function
ax(){var
a=0;for(var
b
in
p)if(p[b].opened)a=[0,p[b],a];return a}function
az(a){return a
instanceof
Array?a[0]:a
instanceof
h?252:M}function
b(a,b,c){f[a+1]=b;if(c)f[c]=b}var
ay={};function
ap(a){if((a.t&6)!=0)_(a);return a.c}function
aC(a,b){ay[ap(a)]=b;return 0}b(11,[a,c(J),-12],J);b(10,[a,c(E),-11],E);b(9,[a,c(P),-10],P);b(8,[a,c(S),-9],S);b(7,[a,c(O),-8],O);b(6,[a,c(R),-7],R);b(5,[a,c(N),-6],N);b(4,[a,c(U),-5],U);b(3,[a,c(W),-4],W);b(2,[a,c(T),-3],T);b(1,[a,c(L),-2],L);b(0,[a,c(D),-1],D);m(0);aw(0);ac(1);ac(2);m(0);m(0);m(0);var
y=[0,0],al=c("Js.Error"),am=c("_elm_lang$virtual_dom$Native_VirtualDom.text"),an=c("_elm_lang$core$Native_Platform.addPublicModule"),ao=c("Hello World!");function
z(a){y[1]=[0,a,y[1]];return 0}var
ak=w.Array,A=[a,al,m(0)],r=[0,A,{}],aj=az(r)===a?r:r[1];aC(c("jsError"),aj);z(function(a){return a[1]===A?[0,ab(a[2].toString())]:0});z(function(a){return a
instanceof
ak?0:[0,ab(a.toString())]});function
B(a,b){return au(as(a),b)}var
C={};B(an,[0,C,"Main",{"main":B(am,[0,ao])}]);C.fullscreen();function
ai(a){var
b=a;for(;;){if(b){var
c=b[2],d=b[1];try{av(d)}catch(f){}var
b=c;continue}return 0}}ai(ax(0));return}(function(){return this}()));
