
// Generated by js_of_ocaml 2.7
(function(y){"use strict";var
M="Sys_error",Z=224,Y="Invalid_argument",m=1024,L=57343,X=512,W="End_of_file",U="_elm_lang$core$Native_Platform.batch",V="Failure",K="Undefined_recursive_module",T="Stack_overflow",e=128,d="",u=" : file already exists",H=56320,I=240,J=2048,a=248,S="Not_found",F="Assert_failure",G="/",Q="Sys_blocked_io",R="fd ",E="Out_of_memory",P="Match_failure",O="Division_by_zero",N=1e3,aL=0;function
n(){return aL++}function
aP(a,b){if(b.repeat)return b.repeat(a);var
c=d,e=0;if(a==0)return c;for(;;){if(a&1)c+=b;a>>=1;if(a==0)return c;b+=b;e++;if(e==9)b.slice(0,1)}}function
aj(a,b,c){var
e=new
Array(c);for(var
d=0;d<c;d++)e[d]=a[b+d];return e}function
x(a,b,c){var
e=String.fromCharCode;if(b==0&&c<=4096&&c==a.length)return e.apply(null,a);var
f=d;for(;0<c;b+=m,c-=m)f+=e.apply(null,aj(a,b,Math.min(c,m)));return f}function
aa(a){if(a.t==2)a.c+=aP(a.l-a.c.length,"\0");else
a.c=x(a.c,0,a.c.length);a.t=0}function
ac(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>127)return false;return true}else
return!/[^\x00-\x7f]/.test(a)}function
aU(a){for(var
l=d,f=d,i,h,j,b,c=0,k=a.length;c<k;c++){h=a.charCodeAt(c);if(h<e){for(var
g=c+1;g<k&&(h=a.charCodeAt(g))<e;g++);if(g-c>X){f.substr(0,1);l+=f;f=d;l+=a.slice(c,g)}else
f+=a.slice(c,g);if(g==k)break;c=g}b=1;if(++c<k&&((j=a.charCodeAt(c))&-64)==e){i=j+(h<<6);if(h<Z){b=i-12416;if(b<e)b=1}else{b=2;if(++c<k&&((j=a.charCodeAt(c))&-64)==e){i=j+(i<<6);if(h<I){b=i-925824;if(b<J||b>=55295&&b<57344)b=2}else{b=3;if(++c<k&&((j=a.charCodeAt(c))&-64)==e&&h<245){b=j-63447168+(i<<6);if(b<65536||b>1114111)b=3}}}}}if(b<4){c-=b;f+="\ufffd"}else
if(b>65535)f+=String.fromCharCode(55232+(b>>10),H+(b&1023));else
f+=String.fromCharCode(b);if(f.length>m){f.substr(0,1);l+=f;f=d}}return l+f}function
aT(a){switch(a.t){case
9:return a.c;default:aa(a);case
0:if(ac(a.c)){a.t=9;return a.c}a.t=8;case
8:return aU(a.c)}}function
h(a,b,c){this.t=a;this.c=b;this.l=c}h.prototype.toString=function(){return aT(this)};function
ai(a){if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
b=y.console;b&&b.error&&b.error(a)}function
aD(a){ai("caml_js_expr: fallback to runtime evaluation");return eval(a.toString())}function
aE(a){return aj(a,1,a.length-1)}function
aF(a,b){return a.apply(null,aE(b))}function
aV(a){for(var
h=d,c=h,b,j,f=0,i=a.length;f<i;f++){b=a.charCodeAt(f);if(b<e){for(var
g=f+1;g<i&&(b=a.charCodeAt(g))<e;g++);if(g-f>X){c.substr(0,1);h+=c;c=d;h+=a.slice(f,g)}else
c+=a.slice(f,g);if(g==i)break;f=g}if(b<J){c+=String.fromCharCode(192|b>>6);c+=String.fromCharCode(e|b&63)}else
if(b<55296||b>=L)c+=String.fromCharCode(Z|b>>12,e|b>>6&63,e|b&63);else
if(b>=56319||f+1==i||(j=a.charCodeAt(f+1))<H||j>L)c+="\xef\xbf\xbd";else{f++;b=(b<<10)+j-56613888;c+=String.fromCharCode(I|b>>18,e|b>>12&63,e|b>>6&63,e|b&63)}if(c.length>m){c.substr(0,1);h+=c;c=d}}return h+c}function
ad(a){var
b=9;if(!ac(a))b=8,a=aV(a);return new
h(b,a,a.length)}function
aM(a,b){throw[0,a,b]}function
c(a){return new
h(0,a,a.length)}function
ag(a,b){aM(a,c(b))}var
f=[0];function
g(a){ag(f.Sys_error,a)}function
aG(a){if(!a.opened)g("Cannot flush a closed channel");if(a.buffer==d)return 0;if(a.output)switch(a.output.length){case
2:a.output(a,a.buffer);break;default:a.output(a.buffer)}a.buffer=d;return 0}function
ab(a){ag(f.Invalid_argument,a)}function
l(a){if(a<0)ab("String.create");return new
h(a?2:9,d,a)}var
ah=0;function
aX(){return new
Date().getTime()/N}function
z(){return Math.floor(aX())}function
i(a){this.data=a;this.inode=ah++;var
b=z();this.atime=b;this.mtime=b;this.ctime=b}i.prototype={truncate:function(){this.data=l(0);this.modified()},modified:function(){var
a=z();this.atime=a;this.mtime=a}};function
w(a){return a.l}function
af(a){a=a
instanceof
h?a.toString():a;g(a+": No such file or directory")}var
aB=G;function
q(a){a=a
instanceof
h?a.toString():a;if(a.charCodeAt(0)!=47)a=aB+a;var
e=a.split(G),b=[];for(var
c=0;c<e.length;c++)switch(e[c]){case"..":if(b.length>1)b.pop();break;case".":break;case"":if(b.length==0)b.push(d);break;default:b.push(e[c]);break}b.orig=a;return b}function
j(){this.content={};this.inode=ah++;var
a=z();this.atime=a;this.mtime=a;this.ctime=a}j.prototype={exists:function(a){return this.content[a]?1:0},mk:function(a,b){this.content[a]=b},get:function(a){return this.content[a]},list:function(){var
a=[];for(var
b
in
this.content)a.push(b);return a},remove:function(a){delete
this.content[a]}};var
s=new
j();s.mk(d,new
j());function
v(a){var
b=s;for(var
c=0;c<a.length;c++){if(!(b.exists&&b.exists(a[c])))af(a.orig);b=b.get(a[c])}return b}function
aS(a){var
c=q(a),b=v(c);return b
instanceof
j?1:0}function
aQ(a){return new
h(4,a,a.length)}function
$(a){var
c=new
Array(a.l),e=a.c,d=e.length,b=0;for(;b<d;b++)c[b]=e.charCodeAt(b);for(d=a.l;b<d;b++)c[b]=0;a.c=c;a.t=4;return c}function
aY(a){if(a.t!=4)$(a);return a.c}function
aC(a,b){var
f=q(a),d=s;for(var
k=0;k<f.length-1;k++){var
e=f[k];if(!d.exists(e))d.mk(e,new
j());d=d.get(e);if(!(d
instanceof
j))g(f.orig+u)}var
e=f[f.length-1];if(d.exists(e))g(f.orig+u);if(b
instanceof
j)d.mk(e,b);else
if(b
instanceof
i)d.mk(e,b);else
if(b
instanceof
h)d.mk(e,new
i(b));else
if(b
instanceof
Array)d.mk(e,new
i(aQ(b)));else
if(b.toString)d.mk(e,new
i(c(b.toString())));else
ab("caml_fs_register");return 0}function
aR(a){var
b=s,d=q(a),e,f;for(var
c=0;c<d.length;c++){if(b.auto){e=b.auto;f=c}if(!(b.exists&&b.exists(d[c])))return e?e(d,f):0;b=b.get(d[c])}return 1}function
o(a,b,c){if(f.fds===undefined)f.fds=new
Array();c=c?c:{};var
d={};d.file=b;d.offset=c.append?w(b.data):0;d.flags=c;f.fds[a]=d;f.fd_last_idx=a;return a}function
aZ(a,b,c){var
d={};while(b){switch(b[1]){case
0:d.rdonly=1;break;case
1:d.wronly=1;break;case
2:d.append=1;break;case
3:d.create=1;break;case
4:d.truncate=1;break;case
5:d.excl=1;break;case
6:d.binary=1;break;case
7:d.text=1;break;case
8:d.nonblock=1;break}b=b[2]}var
h=a.toString(),j=q(a);if(d.rdonly&&d.wronly)g(h+" : flags Open_rdonly and Open_wronly are not compatible");if(d.text&&d.binary)g(h+" : flags Open_text and Open_binary are not compatible");if(aR(a)){if(aS(a))g(h+" : is a directory");if(d.create&&d.excl)g(h+u);var
i=f.fd_last_idx?f.fd_last_idx:0,e=v(j);if(d.truncate)e.truncate();return o(i+1,e,d)}else
if(d.create){var
i=f.fd_last_idx?f.fd_last_idx:0;aC(a,l(0));var
e=v(j);return o(i+1,e,d)}else
af(a)}o(0,new
i(l(0)));o(1,new
i(l(0)));o(2,new
i(l(0)));function
aH(a){var
b=f.fds[a];if(b.flags.wronly)g(R+a+" is writeonly");return{file:b.file,offset:b.offset,fd:a,opened:true,refill:null}}function
_(a,b,c,d,e){if(e==0)return 0;if(d==0&&(e>=c.l||c.t==2&&e>=c.c.length)){c.c=a.t==4?x(a.c,b,e):b==0&&a.c.length==e?a.c:a.c.substr(b,e);c.t=c.c.length==c.l?0:2}else
if(c.t==2&&d==c.c.length){c.c+=a.t==4?x(a.c,b,e):b==0&&a.c.length==e?a.c:a.c.substr(b,e);c.t=c.c.length==c.l?0:2}else{if(c.t!=4)$(c);var
g=a.c,h=c.c;if(a.t==4)for(var
f=0;f<e;f++)h[d+f]=g[b+f];else{var
i=Math.min(e,g.length-b);for(var
f=0;f<i;f++)h[d+f]=g.charCodeAt(b+f);for(;f<e;f++)h[d+f]=0}}return 0}function
aW(a){if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
b=y.console;b&&b.log&&b.log(a)}var
r=new
Array();function
aO(a,b){var
h=c(b),d=w(h),g=w(a.file.data),f=a.offset;if(f+d>=g){var
e=l(f+d);_(a.file.data,0,e,0,g);_(h,0,e,f,d);a.file.data=e}a.offset+=d;a.file.modified();return 0}function
ae(a){var
b;switch(a){case
1:b=aW;break;case
2:b=ai;break;default:b=aO}var
e=f.fds[a];if(e.flags.rdonly)g(R+a+" is readonly");var
c={file:e.file,offset:e.offset,fd:a,opened:true,buffer:d,output:b};r[c.fd]=c;return c}function
aI(){var
a=0;for(var
b
in
r)if(r[b].opened)a=[0,r[b],a];return a}function
aK(a){return a
instanceof
Array?a[0]:a
instanceof
h?252:N}function
b(a,b,c){f[a+1]=b;if(c)f[c]=b}var
aJ={};function
aA(a){if((a.t&6)!=0)aa(a);return a.c}function
aN(a,b){aJ[aA(a)]=b;return 0}b(11,[a,c(K),-12],K);b(10,[a,c(F),-11],F);b(9,[a,c(Q),-10],Q);b(8,[a,c(T),-9],T);b(7,[a,c(P),-8],P);b(6,[a,c(S),-7],S);b(5,[a,c(O),-6],O);b(4,[a,c(W),-5],W);b(3,[a,c(Y),-4],Y);b(2,[a,c(V),-3],V);b(1,[a,c(M),-2],M);b(0,[a,c(E),-1],E);n(0);aH(0);ae(1);ae(2);n(0);n(0);n(0);var
A=[0,0],an=c("Js.Error"),ao=c("_elm_lang$core$Native_Json.decodePrimitive"),ap=c("string"),aq=c("int"),ar=c("float"),as=c("bool"),au=c("_elm_lang$virtual_dom$Native_VirtualDom.node"),at=c("_elm_lang$virtual_dom$Native_VirtualDom.text"),aw=c(U),av=c(U),ax=c("div"),ay=c("_elm_lang$core$Native_Platform.addPublicModule"),az=c("AAAA");function
B(a){A[1]=[0,a,A[1]];return 0}var
am=y.Array,C=[a,an,n(0)],t=[0,C,{}],al=aK(t)===a?t:t[1];aN(c("jsError"),al);B(function(a){return a[1]===C?[0,ad(a[2].toString())]:0});B(function(a){return a
instanceof
am?0:[0,ad(a.toString())]});function
k(a,b){return aF(aD(a),b)}function
p(a){return k(ao,[0,a])}p(ap);p(aq);p(ar);p(as);k(av,[0,0]);k(aw,[0,0]);var
D={};k(ay,[0,D,"Main",{"main":k(au,[0,ax,0,[0,k(at,[0,az]),0]])}]);D.fullscreen();function
ak(a){var
b=a;for(;;){if(b){var
c=b[2],d=b[1];try{aG(d)}catch(f){}var
b=c;continue}return 0}}ak(aI(0));return}(function(){return this}()));
